[build]
  publish = "."
  command = ""

# Ensure proper headers for JSON files
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "max-age=0, must-revalidate"

# Handle 404s for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  
# But don't redirect API calls or static files
[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200